### ISSUE TITLE
TagHelper tooling does not work with pre-compilation enabled.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/RazorTooling#10]
Today if a project has pre-compilation enabled with `TagHelper`s contained it "may" not build. I specify "may" because it seems inconsistent for when a binary load exception occurs.

**Comment by Eilon** [comment]
@pranavkm ,  @NTaylorMullen says you're already working on this.

**Comment by pranavkm** [comment]
This might likely already be fixed. I just need to verify this.

**Comment by Eilon** [comment]
Cool.

**Comment by pranavkm** [comment]
Not seeing issues here with the precompilation changes.

**Comment by NTaylorMullen** [comment]
:+1:
