### ISSUE TITLE
Remove ViewComponent tag helper workaround when VS packages are updated

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/RazorTooling#100]
PR #99 is a workaround to make design time for ViewComponent tag helpers work without needing VS update. Once VS packages are updated, this workaround is no longer needed.

cc @NTaylorMullen @Eilon

**Comment by Eilon** [comment]
@ajaybhargavb @NTaylorMullen when theoretically can we do this? That is, at what time do we expect "the VS packages to be updated"?

**Comment by NTaylorMullen** [comment]
@Eilon when a new WTE is shipped 😄

**Comment by Eilon** [comment]
Assigning to @ajaybhargavb to remove ONCE we have a new WTE that has the new bits.

**Comment by ajaybhargavb** [comment]
Related issue https://github.com/aspnet/RazorTooling/issues/106

**Comment by ajaybhargavb** [comment]
Can this be closed as this is no longer applicable?

**Comment by NTaylorMullen** [comment]
We aren't maintaining this repo anymore so I'd say we could close everything here 😄. That's up to @Eilon though.
