### ISSUE TITLE
Intellisense from output folder

### ISSUE THREAD

**Issue by AbubakerB** [aspnet/RazorTooling#103]
Hi guys,

I don't know if this is the correct place to raise this but I'm trying to get intellisense from razor files in non-web projects and its just not working.
I'm using tools like RazorEngine/RazorTemplate/RazorLight and the only way to get intellisense is to copy their dlls to the \bin folder. I read that the reason for this is because VS only looks at the \bin directory because, of course, that's the default output folder for web-projects.
But for example, console apps, have their output in \bin\debug or \bin\release. Is there a way to make this work atm (with VS2015.3)? Or is there a reason to why it only looks in the bin folder?
If it's not already fixed, could it be fixed?

I've searched everywhere for an answer on this but all I can find are people saying copy to bin folder.

**Comment by NTaylorMullen** [comment]
@AbubakerB there currently is not a way to do this by default for non-web projects. Sorry that there's not a better answer 😢

**Comment by AbubakerB** [comment]
That's alright, thanks for the response.
Would it be possible to make this work for the upcoming VS "15"?

**Comment by NTaylorMullen** [comment]
We're currently rethinking the way the Razor editor works and have started prototyping. In this "new" world having support for class libraries would definitely be something on our radar.

**Comment by AbubakerB** [comment]
Awesome! Looking forward to it!

**Comment by Eilon** [comment]
This issue was moved to aspnet/Razor#1134
