### ISSUE TITLE
Add tests that target the latest version of Razor.Runtime

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/RazorTooling#109]
From https://github.com/aspnet/RazorTooling/pull/108#discussion_r85584480

We changed the tool to target 1.0.0 version of razor runtime. We need tests that target both 1.0.0 and 1.1.0-\* versions of Razor.Runtime to make sure the tool works in both cases.

**Comment by Eilon** [comment]
This issue was moved to aspnet/Razor#1133
