### ISSUE TITLE
Bundle deps.json to future proof RazorTooling

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/RazorTooling#112]
In coming releases of NuGet they'll be utilizing the deps.json to properly restore tools. We should bundle the deps.json early to ensure the tool continues to work.

**Comment by Eilon** [comment]
@NTaylorMullen @natemcmaster @muratg what's the timeline for getting this in? Taylor is OOF until Friday, so if more urgent than that, we'll need another person to handle this.

**Comment by NTaylorMullen** [comment]
Are the CLI folks shipping new versions of CLI that work with `project.json` that also require the deps.json? If so we'll need to complete this issue. Otherwise, this issue doesn't matter because the Razor tooling doesn't work with MSBuild based projects.

**Comment by Eilon** [comment]
Oh, right, this Razor Tooling is going away in its current form... I'm guessing the answer to your question is that there wouldn't be such a CLI. @natemcmaster is that your understanding?

**Comment by natemcmaster** [comment]
> there wouldn't be such a CLI. 

Yes, that was my understanding as well.

**Comment by Eilon** [comment]
Ok, then closing this. Thanks!
