### ISSUE TITLE
Question: Can I View Generated Source From Precompiled Views?

### ISSUE THREAD

**Issue by MisterJames** [aspnet/RazorTooling#114]
I am looking for a way to inspect the source of the view classes, post-compilation. 

From the DLL that is generated, when I try to look at it with a decompiler it says it's not a valid DLL (tried this with Telerik JustDecompile). 

I was looking for a way to perhaps write the source to disk or some other way to drill in. I was going to try to follow the code path, but RazorTooling doesn't build after cloning, so that wasn't a straightforward path (though I'm not opposed to working on getting that going along with Razor proper). 

Any suggestions?

**Comment by NTaylorMullen** [comment]
Answered via twitter convo: https://twitter.com/ntaylormullen/status/805853661792444418
