### ISSUE TITLE
Razor Tag Intellisense disappears

### ISSUE THREAD

**Issue by vankampenp** [aspnet/RazorTooling#116]
### Title
Razor Tag Intellisense disappears when upgrading to  "1.1.0-preview4-final"

### Functional impact
Razor Tag intellisense disappears, and cannot be restored for the existing project. 

### Minimal repro steps
1. Create a new ASP.NET Core Project. Select ASP.NET Core Web Application (.NET Framework)
2. Choose No authentication
3. Build the web application
4. In a view type <a asp // notice that the Intellisense works
5. In the PM Console do: Update-Package
6. In a view type <a asp // notice that the intellisense still works
7. In the PM Console do: Install-Package Microsoft.AspNetCore.Razor.Tools -Pre
9. In a view type <a asp // notice that the intellisence still works, but not for Razor Tags
10. do: Uninstall-Package Microsoft.AspNetCore.Razor.Tools
11. do: Install-Package Microsoft.AspNetCore.Razor.Tools -Pre
12. Build
13. In a view, notice that inspite of having the same packages as in step 6, Intellisense for tags does not work
### Expected result
Razor Tag Intellisense should be there after upgrading, and downgrading should restore the state
### Actual result
Intellisense only shows other info, not from Razor Tags (no asp, no color highlighting).

**Comment by Eilon** [comment]
@vankampenp sorry for the delay responding to you. Are you using VS2015 or VS2017?

It sounds to me like you're using VS2017, in which case we had to temporarily remove tag helper Intellisense due to time constraints, but we are working on bringing it back as soon as possible. We plan to have a preview download of a tag helper Intellisense add-in that will restore this behavior in VS2017, and it will later be part of a VS2017 update.

**Comment by vankampenp** [comment]
Hi, I am using VS2015

**Comment by Eilon** [comment]
@NTaylorMullen any thoughts on this?

**Comment by NTaylorMullen** [comment]
The reason why this is happening is when you uninstall the `Microsoft.AspNetCore.Razor.Tools` it nukes the `dependencies` section reference and the `tools` section reference. Then upon re-installing the package it only goes into the `dependencies` section. If you are to re-add: `"Microsoft.AspNetCore.Razor.Tools": "1.1.0-preview4-final"` to the `tools` section all continues to work.
