### ISSUE TITLE
IRazorViewEngine does not pick updated cshtml

### ISSUE THREAD

**Issue by KhalilMohammad** [aspnet/RazorTooling#121]
I am converting cshtml to pdf.
I am using IRazorViewEngine.
IRazorViewEngine is picking old view.
Dotnet watch does not work for this scenario.
Is there any work around, I have multiple cshtml to work on

**Comment by KhalilMohammad** [comment]
I am using [RazorViewToStringRenderer](https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.RenderViewToString/RazorViewToStringRenderer.cs)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @KhalilMohammad.
@NTaylorMullen , can you please look into this one? Thanks!

**Comment by NTaylorMullen** [comment]
@KhalilMohammad how are you using RazorViewToStringRenderer? Aka, are you lifting that method directly into your site? That samples normal usage scenario is run once and then it goes away (an exe) so i'll need more context 😄

**Comment by KhalilMohammad** [comment]
I use this generate pdf from html.
In production ,It will be run once.
In development, I need to change html to get perfect alignment.

**Comment by mkArtakMSFT** [comment]
@KhalilMohammad, can you please provide a repro project to simplify the investigation?

**Comment by mkArtakMSFT** [comment]
This issue was moved to aspnet/Razor#2305
