### ISSUE TITLE
Move from using `IAssemblyLoadContext` => `AssemblyLoadContext`

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/RazorTooling#29]
We're moving Razor assembly loading from `IAssemblyLoadContext` => `AssemblyLoadContext` in MVC. We need to also accomplish this in this repo to ensure `TagHelperDescriptor` assemblies continue to load.

@muratg

**Comment by muratg** [comment]
:+1:

**Comment by NTaylorMullen** [comment]
Talked with @davidfowl and this wont be able to make it into RC1 and work. Need to punt this to RC2

**Comment by NTaylorMullen** [comment]
3de479b156c2bf9822735472fd5d2d348485de41
