### ISSUE TITLE
Refactor code to enable testing on CoreCLR

### ISSUE THREAD

**Issue by cesarbs** [aspnet/RazorTooling#30]
Add this to test\Microsoft.AspNet.Tooling.Razor.Test\project.json:

    "dnxcore50": {
      "dependencies": {
        "System.Dynamic.Runtime": "4.0.11-beta-*"
      }
    }

Two code changes are necessary:

* In RazorPluginTest.cs, use Type.GetTypeInfo().Assembly instead of Type.Assembly.
* It is not possible to subclass Assembly in CoreCLR. Change the code to use an interface instead of direcly using Assembly objects.

This is related to https://github.com/aspnet/Universe/issues/304.

**Comment by NTaylorMullen** [comment]
Going to complete https://github.com/aspnet/RazorTooling/issues/25 prior to this since the code will be drastically changing

**Comment by NTaylorMullen** [comment]
5a469ade43e1747bffa034ff19e3be69e01e2a31
