### ISSUE TITLE
Add ability to specify if TagHelperDescriptors should be resolved in design time or runtime.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/RazorTooling#59]
Today `TagHelperDescriptor`s are always resolved as if it were design time. It could be useful to enable overriding that functionality.

**Comment by Eilon** [comment]
Useful for what?

**Comment by NTaylorMullen** [comment]
It could enable you to pre-determine `TagHelperDescriptor`s for an application at runtime. In general it's just for flexibility. The ability for any tool to determine `TagHelperDescriptor`s on any platform without having to spin up entire websites to do the work.

**Comment by Eilon** [comment]
🌘
