### ISSUE TITLE
Create end-to-end functional test to validate dotnet-razor-tooling functionality.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/RazorTooling#62]
Command line applications today are not easy to test. Also, with the recently added dispatch logic testing is even more difficult. Nevertheless we should still create an end-to-end functional test to ensure we don't regress anything. It will do:

1. Pack dotnet-razor-tooling
1. Build a local package directory to use for the test
1. dotnet restore the test project
1. dotnet build the test project
1. Invoke dotnet-razor-tooling on the test project.
1. Cleanup or git ignore any artifacts.

**Comment by Eilon** [comment]
Moving to 1.0.1

**Comment by NTaylorMullen** [comment]
Gonna wait to complete this one until [this](https://github.com/aspnet/RazorTooling/issues/80) has been completed.

**Comment by NTaylorMullen** [comment]
1cc4498a933c562c411be4094277ec87cb51f221
