### ISSUE TITLE
Enable RazorTooling to resolve TagHelpers for non-desktop, package assemblies.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/RazorTooling#70]
Currently RazorTooling requires a project to be built before any TagHelpers can be resolved. However, if we check if the assembly requested to be resolved is not desktop and is a package with a package-only graph then we can create a load context without having to dispatch to the inside-man. Aka, we wouldn't need to build.

**Comment by Eilon** [comment]
@DamianEdwards do you want this for v1? It's ultimately a tooling thing so we have a bit more time than runtime v1.

**Comment by DamianEdwards** [comment]
Yes, we need to solve this for v1 tooling.

**Comment by Eilon** [comment]
Ok, putting in a `1.0.1` milestone for now.

**Comment by NTaylorMullen** [comment]
cae1d5ac2546d8bbe05cb8b1516f6c08ad0f89b9
