### ISSUE TITLE
When opening a solution, TagHelpers are not lit up for cshtml files previously opened.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/RazorTooling#9]
If you close a solution with open cshtml files that happen to have `TagHelper`s lit up in them. Reopening that solution will result in the same cshtml file being opened for you, but no TagHelper intellisense.

**Comment by Eilon** [comment]
@NTaylorMullen please verify this with the latest build.

**Comment by Eilon** [comment]
If it's still an issue please log a bug in the Tooling repo.

**Comment by Eilon** [comment]
@NTaylorMullen can you have a look at this one today to see where the issue might be?

**Comment by NTaylorMullen** [comment]
This is no longer an issue.
