### ISSUE TITLE
Restore fails on CI test

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/RazorTooling#94]
Similar to https://github.com/aspnet/MvcPrecompilation/issues/3.
The custom `repo-initialize` target does not take into account the fact that the `src` folder is deleted when we are running tests on the CI. We delete the `src` folders to skip rebuilding the packages but that also means the tests will fail during this step: https://github.com/aspnet/RazorTooling/blob/dev/makefile.shade#L30.

**Comment by JunTaoLuo** [comment]
cc @pranavkm @NTaylorMullen

**Comment by pranavkm** [comment]
I added this repo to the no-src-exclude thing. This should fix this issue for now.

**Comment by Eilon** [comment]
@pranavkm anything left to do here?

**Comment by pranavkm** [comment]
Nope
