### ISSUE TITLE
Msbuildify tools

### ISSUE THREAD

**Issue by muratg** [aspnet/RazorTooling#97]
### Microsoft.AspNetCore.Razor.Tools
- Expect to run in the IDE 
- Runtime dependencies/Load Context thingy
- Including type (project, package, etc.)
- TargetPath
### TODO
- Fork tools repos to `rel/1.0.0-preview3` branches for "October" release. Dev branches will continue to be used for 1.1 release.
- Use desktop msbuild to start our work until the new msbuild is ready for   consumption
### Notes
- [This](https://github.com/aspnet/Coherence-Signed/issues/375) tracks the work across the tools repos.
- [This](https://github.com/aspnet/specs/blob/master/notes/Tools.md) is the previous discussion on the topic.

**Comment by NTaylorMullen** [comment]
Taking a different approach to RazorTooling. Will be utilizing Razor server to do the tooling work.
